name: Lint
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: WoW Lua lint
        uses: davidcraig/action-wow-lint@v1.0.1
        with:
            path-to-files: 'DerangementPetBattleCooldowns.lua'

      - name: Lint XML
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: ./DerangementPetBattleCooldowns.xml
          xml-schema-file: ./UI.xsd
